### ISSUE TITLE
Fill in Roman transliterations of Cyrillic entries for Slav languages.

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#120]
Old Church Slavonic
Bulgarian
Macedonian
Belarusian
Ukranian

**Comment by morenovuleta** [comment]
All five languages transliterated

**Comment by leszekjocz** [comment]
I am not sure if the transliterations are really satysfiyng.
What we have now, is in my opinion a strange and inconsistent mixture of the "scientific Slavic" transliteration (e.g. the sh-sounds), the popular "English" transliteration used in Russian passports (e.g. kh, ts) and some your personal ideas (e.g. Macedonian ќ, ѓ).

**Comment by cormacanderson** [comment]
Thanks @morenovuleta for doing this so quickly, and @leszekjocz for giving feedback so rapidly as well. If you are both willing, I think the best thing to do would be for the two of you to confer on a standard for each language and Moreno if you could change accordingly.
With respect to "Serbo-Croatian", could we use Cyrillic as the orthographic form and Latin for the transliteration? Or what would you suggest in that instance?
I am reopening this issue in light of Leszek's comments.

**Comment by morenovuleta** [comment]
So, as far as I am aware, both "sh" and "š", and related are acceptable forms in transliteration, however I opted for forms with a haček on top because it is more pleasing to the eye, especially if there is a long word. I`ve decided to write the velar fricative phoneme "kh" as such in all five language due to a specific reason - namely, all five languages consistently pronounce their "hs" as velar fricatives, unlike my native variety, which features an "h" that is either a glottal fricative or an approximant if I recall correctly, but anyway, quite different. That is why I decided to distinguish the two in writing. 
Secondly, I think I will convert all the "ts" into "c", there was no reason for "ts" as "c" is readily used in latin ortography. 
Regarding transliteration of certain Macedonian characters, well, that is how they usually do it in practice, and other conventions are recognized as well - I can be flexible about that, any seems fine to me. 

@cormacanderson
I am quite sure there is no need for that; there is really no effect to that, and people in Serbia readily use latin script in all contexts on a daily basis - the country is in effect biscriptal

**Comment by cormacanderson** [comment]
I think here that it would be best to use an accepted standard, perhaps the traditional scientific transliteration that Leszek outlines. Furthermore, we should write up clear guidelines as to the correspondences. This should not be done in an ad hoc way.

**Comment by morenovuleta** [comment]
Sure, I can agree to that.

**Comment by leszekjocz** [comment]
All the transliterations systems mentioned above are "acceptable" but I'm not sure if we really should use an ad-hoc mixture of them. In my opinion it is much better to discuss the whole thing and only then begin to work and not the other way around. Of course some problems occur only in the flow of work but we still need solide starting points.
We have a couple of possibilities here:
- The popular Khrushchev-like transliteration. Its only advantage is that it's readable for all who can read English. However, I'm pretty sure that this system is uncapable to cover all needed lettters for all relevant Slavic orthographies (and I expect that we will have other cyrillic orthographies in our database too) and it surely does not work for ancient languages. What's also important is that it's rather not regarded as a "serious" or "professional" system by many slavists. It's rather something for very practical purposes and I have my doubts if it really fits a place like our database.
- ISO. It is universal for all (?) modern languages but it does not have signs for the ancient languages. It is not so widespread and not so well known, I think. In some cases it is quite abstract but it is not a serious problem if we have phonetic and phonological transcriptions.
- The traditional scientific transliteration. As far as I can judge now it has all that we need. However, it can be not so easily intelligible for non-slavists (but I think it's an unavoidable problem for other languages/families that use non-Latin scripts too). For some cases (like yers) cyrillic letters are normally used (but there are also Latin alternatives).
I dont mention the question of the coding, I think is a minor problem today.

**Comment by m-scarborough** [comment]
The issue that Leszek raises on the availability of established standards for ancient and modern language distinction is an important one.  

If I may weigh in on the issue on the basis of what I did for the Greek languages, I used an ISO standard for the transliteration of the modern language, but a more traditional scientific one for the Ancient language where there is no ISO transliteration.  The standard I used for the ancient language was the American Library Association / Library of Congress standard, slightly adapted since I added accentual diacritics to the Roman transliteration.  

In general practice, I would like to suggest that we use the ISO where it exists, but for the ancient languages to use some other acceptable scientific or bibliographic standard which should be specified in the language description.  The source for the ALA-LC recommended transliteration systems which I used for the Ancient Greek is on their website: http://www.loc.gov/catdir/cpso/roman.html  They also have several other recommended systems for ancient languages that we have in the database (including Old Church Slavic).

Of course, as Leszek rightly points out, the ISO transliteration systems for the modern languages tend to be more abstract, but the attached phonetic and phonological analyses should clarify any issues of linguistic interpretation.  The purposes of the transliterations are, after all, more for data accessibility than anything else, so I wouldn't think it shouldn't be too much of a problem.

**Comment by cormacanderson** [comment]
By the sounds of it, ISO where available, and then specific standards for older languages, where it is not, as @m-scarborough suggests, is the best solution here. @leszekjocz are you happy with that? We should either write up the correspondences, or else link to a webpage where they are laid out, like the one Matthew provides there. I will send an email now to Leszek and Moreno so you can confer on the Slavic transliterations.

**Comment by PaulHeggarty** [comment]
Very impressed by the speed of responses on all this.  I absolutely agree:  we must use standards, not just personal approaches!  And yes, ISO where available, unless there is a very good reason for there being an existing, much more common alternative.  
Basically, I think we should go with Leszek's suggestions, and implement them fully and very rigorously.
Above all, no Russian 'passport style' transliterations, which are a complete joke. I become a whole range of things, such as  Pol Gegarti.  They’re not even consistent with the same name.

**Comment by morenovuleta** [comment]
Right, I have gone through the comments, and I do not have much else to say. I will gladly follow Matthew`s and Leszek´s suggestions when I start tweaking up transliterations.

**Comment by morenovuleta** [comment]
Updated:
Old Church Slavonic
Bulgarian
Macedonian
Belarusian
Ukranian

**Comment by leszekjocz** [comment]
I took a short look on the new versions. What do I see in Ukrainian, for example, is:
"боятися" "bojatisja" instead of "boâtisâ"
"живіт" "živit" instead of "živìt"
"тяжкий" "tjažkij" instead of "tâžkij"
"дім" "dim" instead of "dìm"
etc. etc.
There are similar mistakes in the other languages too.

**Comment by leszekjocz** [comment]
Macedonian "јајце" "jajce" instead of "ǰaǰce", Bulgarian "гръб" "grăb" instead of "gr"b", Belarussian "вялікі" "vjaliki" instead of "vâlìkì" etc. etc.

**Comment by morenovuleta** [comment]
All five languages updated
