### ISSUE TITLE
Both Mg list *and* Lg list drop-down selectors should *always* show in top header bar

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#127]
Currently the top header bar has:
[List:]  then a drop-down box for language list

What it should have (as with [Rfc:] then [Branches icon], [Languages] and [Meanings] is:
[Lists:]  then the drop-down box for [Mgs] languages, then the drop-down box for [Lgs]

I think we'll have to start using abbreviations in the header bar too, so please also replace the [Rfc:] texts to:
[Rfc:] then [Branches icon], [Lgs] and [Mgs]

Finally, it would be good to use the same green and blue colours (perhaps as backgrounds to the texts Mgs and Lgs) as used in the 1 Meaning all languages and 1 Language all meanings icons.  It should help people get used to this system and read the icons better.

**Comment by runjak** [comment]
I have problems realizing this for the CoBL default landing page, but will get it solved soon.
For almost all other instances I found a solution on this and will deploy it in time.

**Comment by runjak** [comment]
I currently will not solve this for the nexus export view, because:

* It uses a different structure that I'd want to change
* The nexus view needs to be touched at one point because of performance when exporting
* At the moment I think it is best to leave the nexus view untouched because we need to fix the export anyway.
* The nexus view isn't linked to in the website at the moment, so it's not a big deal anyway.

Except for the nexus export view I think that I have all things in place for this issue to be closed. I will deploy the changes soon.
