### ISSUE TITLE
Add lookup fields of Clade abbreviations corresponding to clade levels

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#131]
In the languages reference form, alongside the Cl 0 field, add an uneditable column that just looks up from the branches table the branch abbreviation that corresponds to that value in Cl 0.

E.g. for Hittite, its Cl 0 value is 1, which corresponds to the Anatolian clade, abbreviation Atl.  
So after the value 1 in Cl 0, next should appear a column with the uneditable entry "Atl".  Best is just to copy the coloured filter button for this branch (but make it unclickable on this form).

Eventually we'll do this for the other levels too.  But let's get this first level working first.  Then leave the issue open so that we complete the other levels later.

**Comment by PaulHeggarty** [comment]
This has already been implemented as tooltips, with the clade name rather than the abbreviation, which is fine.  But ideally this should actually appear as a column of text alongside each Clade number, and always be visible.

**Comment by runjak** [comment]
I've provided an implementation for this that will be deployed at once.
One thing is potentially interesting to note:
While we have names for each clade level I cannot infer abbreviations from these.
For example for `Anatolian` I could generate a prefix `Ana.` but not one `Atl.` because of my limited means of encoding linguistic smartness into programs. For this reason I will use the Clade level names directly, and suggest putting the abbreviations in there. The current entry of Anatolian for example has redundant data here because both the `Clade name` and the `Cl 0 name` are `Anatolian` so for level 0 in the languages table `Anatolian` will be used and `Cl 0 name` would need to be changed to `Atl.` for that to appear.
