### ISSUE TITLE
Clone the languageBranches table

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#153]
The enhancements to the languageBranches table done in #145 turned out to belong to two different tables.
It makes sense to split this up into two separate models and views.
This issue should progress like this:

- [x]  Add a clade table that has the same layout as the languageBranches table.
- [x] Copy the languageBranches data to the clade table.
- [x] Implement a clade view.
- [x]  Adjust the languageBranches and clade tables so that they diverge into two separate things.
- [x] Add clade lookup to SndComp table as requested
- [x] Remove unwanted columns from clade table
- [x] Set default sort order for `Clade` to `Cl {0…3}`
- [x] Set default sort order for `SndComp` to `SC {0…3}`
- [x] Add `Sort Rank Within Clade` to `Language` model
- [x] Add Cl names to clade table
- [x] Add Cl names as lookups to language table
- [x] Make a copy of the current language clade levels. Name these columns sndcomp levels.
- [x] Fix clade lookup for languages

**Comment by PaulHeggarty** [comment]
Effectively as you know, we need two separate tables:  
*	Clade Constraints (for which I suggest .glyphicon-tree-conifer or perhaps better, .glyphicon-random). 
*	SndComp correspondences.  It needs to be clear somehow that this is not a formal part of the data analysis, so that people don’t get the wrong idea.  Best not to tall it ‘branches’ then, or anything similar.  And change the icon to .glyphicon-headphones.  This table should soon be hidden anyway for most users, as soon as we get the Clade constraints one set up.

**Comment by PaulHeggarty** [comment]
For the Clade Constraints table:
- Keep all current fields except the last four (Lv 0 to Lv 3).  
- Rename 'Branch name' to 'Clade Name'.
- The current branch filtering system by the toggle buttons like Rce should to be based on this clade constraint table.

For the SndComp Correspondences table:
- Delete all fields except (Cl 0 to Cl 3), (Lv 0 to Lv 3) and Branch name.  This should basically become just a table of correspondences between CoBL clades and SndComp Lg Sets.  Which is why it should ultimately be hidden from view in any case.
- Rename 'Branch name' to 'SndComp Lg Set Name'.

Reorder fields to:
- SndComp Lg Set Name 
- Lv 0 to Lv 3
- Clade Name [uneditable], looked up from Clade Constraints table on the basis of the (Cl 0 to Cl 3) field values
- Cl 0 to Cl 3

**Comment by PaulHeggarty** [comment]
In both tables the Cl 0 field needs to accept values up to and including 10, currently it is limited to 9.  (There are ten major branches of Indo-European.)

**Comment by PaulHeggarty** [comment]
This table also needs add and delete record buttons, like those in the authors table, perhaps.

**Comment by PaulHeggarty** [comment]
We have just entered quite a lot of data in the existing table, in the Cl 0 to Cl 3 fields.  It would be good if this were not lost when your next changes are deployed.

**Comment by PaulHeggarty** [comment]
Add the tooltips for 'At least' and 'At most'.  No question marks needed on those field names.  (Normally ? is only for a boolean field.)

**Comment by runjak** [comment]
The data from the current language branches table will be copied into the clades table on deployment. Up to that point you can still make changes in the language branches table that will be copied over.

**Comment by runjak** [comment]
The add/delete record buttons are something I've already worked on and have completed on my machine just now.

**Comment by PaulHeggarty** [comment]
Sorry, just thought of another thing we should have.  Very useful for quality control and avoiding errors.  The Cl 0 to Cl 3 levels should each have a text name, e.g. Cl 0 Name, and so on.  Put the name immediately after each the corresponding Cl 0 index number.

Then on the Languages Reference table, these names should appear also alongside the corresponding Cl 0 index numbers, but not as editable:  here they should just be look-ups from the Clades table.

**Comment by runjak** [comment]
Alright, I'm looking into this addition now.
I've almost got a complete SndComp table now with creation and deletion working.
The current todo on this issue looks like this:

- [ ] Add clade lookup to SndComp table as requested
- [ ] Remove unwanted columns from clade table
- [ ] Fix clade lookup for languages
- [ ] Add Cl names to clade table
- [ ] Fix the clade filter

**Comment by PaulHeggarty** [comment]
Yet one more, in case I haven’t already mentioned it:  default sort orders...

- for the Clades table the default sort order should be:  Cl 0 then Cl 1 then Cl 2 then Cl 3.  

- for the Languages Reference table the default sort order should be the same, followed by a new field (integer, up to three digits) called Sort Rank Within Clade, abbreviated in the header to [Sort Ix].  

- for the Branches table, the default sort order should be SC 0 then SC 1 then SC 2 then SC 3

**Comment by runjak** [comment]
Updating my todo list on this issue:
- [x] Add clade lookup to SndComp table as requested
- [x] Remove unwanted columns from clade table
- [ ] Fix clade lookup for languages
- [ ] Add Cl names to clade table
- [ ] Fix the clade filter
- [x] Set default sort order for `Clade` to `Cl {0…3}`
- [x] Set default sort order for `SndComp` to `SC {0…3}`
- [ ] Add `Sort Rank Within Clade` to `Language` model

**Comment by runjak** [comment]
Since fb5ad8058c140825dcf3d1b1c59751ea44c87883 half of the problem in connecting languages to their clades is solved. The problem is in the remaining half:
When a clade is updated this can potentially the relations between all languages and their related clades. In contrast when a language is changed it is only necessary to reconsider it's clades.

**Comment by PaulHeggarty** [comment]
This may be more a theoretical problem than a real one in practice.  We are unlikely to make any significant changes to clades after they are first entered.  Also, even if we do change the definitions of a clade by changing the Cl 0 to Cl 3 fields, if we did so that would be because we actually *want* to change the set of languages it covers, without having to change individual assignments of languages.  So maybe you don’t have to worry about this at all.  We can discuss tomorrow in any case.  It would be good to get this working online as soon as possible.  ;)

**Comment by PaulHeggarty** [comment]
Allow Cl 0 field to accept values up to 10, not just 9.  (There are actually ten major branches of Indo-European, so this is all we need, but we currently can’t input 10 itself.)

**Comment by runjak** [comment]
I'll address the remaining clade filter issues in #154 which will have the clade filter as it's topic and close this issue now. The main focus of this issue is on cloning the language branches table and providing the clades table and that task has been solved.
