### ISSUE TITLE
Fix the home page format problem

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#189]
The photos should *not* appear as a continuation of the last paragraph, but on a separate line, preferably with a divider between them.  I have tried everything on the wiki to make this work, but it fails.

**Comment by runjak** [comment]
The problem here is that markdown isn't standardized very much
so that our markdown rendering differs from the one done by GitHub.
I'll look into our rendering to see if we can get closer to the GitHub representation.
If possible we may be able to use the `-----` marker for horizontal lines,
which would allow us to break the photos from the text.
If this doesn't turn out to be possible I'll look into possible alternatives.

**Comment by runjak** [comment]
To specify:
Our current flavor of Markdown is [CommonMark](http://spec.commonmark.org/).
I'll see if/how I can use it directly to introduce the requested break.

**Comment by runjak** [comment]
Ok - There is a way to write hard line breaks in [CommonMark](http://spec.commonmark.org/0.25/#hard-line-breaks).
I've introduced this into the wiki page, and am currently waiting on the CoBL page to reflect this change.

**Comment by runjak** [comment]
Ok - it appears that the change to the wiki page went trough as hoped.
For future problems of this kind the CommonMark [spec](http://spec.commonmark.org/0.25) should be a useful resource.
To introduce a hard line break, I've appended two spaces to the line before the break,
and followed it by a newline.
