### ISSUE TITLE
Invisible lexemes

### ISSUE THREAD

**Issue by NikosLiosis** [lingdb/CoBL#196]
Every time I try to add a new Tsakonian lexeme the total number of lexemes increases (e.g. from 235 to 236) but the new lexeme is not visible on my wordlist.

**Comment by m-scarborough** [comment]
Hmm.  It looks to me that for some reason when new lexemes are added they default to 'non-Swadesh' status, and since the default view is to filter out non-Swadesh lexemes that's why they're not appearing.   For now this can be toggled off with this button.
<img width="38" alt="screen shot 2016-06-03 at 12 55 32" src="https://cloud.githubusercontent.com/assets/15671787/15777873/88039296-298a-11e6-8a93-346e7166101f.png">
For now this seems rather inconvenient for data input though.  Is there any particular reason this seems to be set as the default in the lexical entry fields @PaulHeggarty @cormacanderson @runjak ?

(NB: alongside 'non-swadesh', I notice 'dubious' is also automatically checked on the new lexeme page.)

**Comment by runjak** [comment]
I think the only reason for the current defaults on lexemes is that they have been this way before. If it's better to have them the other way around I should be able to adjust them without trouble.

**Comment by cormacanderson** [comment]
Hmmm, that shouldn't be happening. New lexemes should be a) Swadesh, and b) not dubious. If you could try to change it @runjak that would be good. Thanks @m-scarborough for chasing this issue up.

**Comment by runjak** [comment]
Alright - I'll see after the defaults when creating lexemes and see to adjust them.

**Comment by runjak** [comment]
It appears that the current (but not deployed) version of the code on my machine already fixes this. I've been working on #184 and commit [9c8c2884](https://github.com/lingdb/CoBL/commit/9c8c2884) reduces the `AddLexemeForm` to take fewer inputs when a lexeme is created.
Old form:
![screenshot_2016-06-08_11-47-55](https://cloud.githubusercontent.com/assets/5417642/15890257/f9b14f5e-2d6e-11e6-95f9-41f75718f0d5.png)
New form:
![screenshot_2016-06-08_11-48-19](https://cloud.githubusercontent.com/assets/5417642/15890264/ff9834aa-2d6e-11e6-9f0f-da5eaa95675d.png)

The problem here was that the old form somehow assumed booleans to be `true` by default, whereas the database was already set to default to `false` for these. So omitting the checkboxes in the creation form lets the defaults work as expected.

I'll close this issue once the update is deployed.

**Comment by runjak** [comment]
I've just deployed the latest state of the website.
