### ISSUE TITLE
Implement a "Merge cognate classes"-function

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#197]
Maybe on the one mean - all cognate classes page? A checkbox similar to the 'split lexemes from a cognate class'-function?

**Comment by runjak** [comment]
Currently working on this.
When merging cognate classes a question arises:
How to fill the fields that have before been filled for each cognate class independently?

I'm thinking a useful approach would be to put into these fields the combined content of the classes being merged.

Say if you tried to merge these two entries:
![screenshot_2016-06-27_12-47-02](https://cloud.githubusercontent.com/assets/5417642/16377261/4bee814c-3c65-11e6-9e09-4bc8666d2cd7.png)
I would let the `Root` entry become something like `{*h₂éh₁s-, spod-}` and the `Root Language` something like `{Proto-Indo-European, Ancient_Greek}` and so on.
This would than need to be fixed by the person that merged the classes, but would have the upside of still retaining the data so that it's easier to edit them.

**Comment by CasFre** [comment]
Yes, I agree with that.
I would also be important to keep the notes and citations from the individual cognate class pages.

**Comment by runjak** [comment]
Yes - fortunately it's easy to keep the citations.
The thing I'm not sure about are fields for checkboxes and numbers so I'm currently leaving these to the default settings for cognate classes.

**Comment by runjak** [comment]
I've just tested merging of cognate classes on my machine with all classes available for ash to see if it works with bigger numbers of classes as well and it does.
![screenshot_2016-06-27_14-25-36](https://cloud.githubusercontent.com/assets/5417642/16379657/1d279048-3c73-11e6-8469-e201b56ae433.png)

I'll now add a simple confirmation dialog to the button and then the programming for this should be done.

**Comment by runjak** [comment]
When visiting the 1 meaning all cognate classes table you should now see a button with two arrows on it next to the `undo` button. You should further be able to select cognate classes to merge and click this button afterwards to merge them.

**Comment by CasFre** [comment]
Yes, I see the button.
Thank you for implementing!
I'll close this issue then and only would re-open it in case of problems.

**Comment by CasFre** [comment]
Two comments on the merger function:
1. It naturally creates a new number for the cognate class that arises after the merger. Do we want to have that in every case, or should we maybe implement a selection menu where we could also decide to keep the number of one of the two cognate classes to be merged? - For this might cause new inconsistencies with cross-references to the contents of the new cognate class within the notes of other cognate classes or individual lexemes.
2. I just merged two cognate classes A and D from meaning [you_pl], and I lost the citation from D. Unfortunately, I can't remember exactly whether there where citations for A (formerly cognate class 349), but I guess there should have been some... @runjak, do you have a version of the database on your machine where the two classes are not merged yet so that you could have a look and maybe re-insert the citations rather easily?

**Comment by runjak** [comment]
Yes, I have older versions of the database on my machine
- I'll have a look what I can do with this.

**Comment by runjak** [comment]
By using the cognate class id `349` I can state that my copy of the database has 2 citations saved for that cognate class:
![screenshot_2016-07-07_11-47-56](https://cloud.githubusercontent.com/assets/5417642/16649345/d2a99ad4-4438-11e6-8ddc-e7cb5dbd4f1d.png)

@CasFre can you state the id of the cognate class that these citation should belong to in the current database? I'll investigate further what the merging function does with citations.

**Comment by runjak** [comment]
So from looking at [views.py:1271-1324](https://github.com/lingdb/CoBL/blob/520418eafb9854554a0628aa00c29d014733da4f/ielex/views.py#L1271-L1324) I think that I overlooked the necessity to merge citations.
This means that citations are currently indeed just dropped when merging cognate classes.
Thanks to @CasFre for spotting this.
I will develop a fix for this feature providing correct merging of citations.

**Comment by CasFre** [comment]
Thank you for investigating into this and fixing it, @runjak.
The cognate class that these citations should now belong to is no. 5822:
http://www.cobl.info/cognate/5822/

**Comment by runjak** [comment]
This is a crude picture of the database layout:
![ER-Diagram](https://cloud.githubusercontent.com/assets/5417642/16651710/19fbc71a-4446-11e6-8fc1-e72176aa848f.png)
While I successfully took into account the `CognateJudgementCitation` table I didn't notice that I also need to take care of the `CognateClassCitation` table when merging cognate classes. The fix will consist of two parts:
* Let the merge function handle `CognateClassCitation` entries correctly.
* Attach the citations that belonged to `349` to cognate class `5822`.

**Comment by runjak** [comment]
I've developed a fix that copies `CognateClassCitation`s as expected.
The original cognate classes:
![screenshot_2016-07-07_13-38-41](https://cloud.githubusercontent.com/assets/5417642/16652182/1808d896-4449-11e6-85af-f756645dcdde.png)
![screenshot_2016-07-07_13-38-50](https://cloud.githubusercontent.com/assets/5417642/16652183/1809a154-4449-11e6-8a8b-4ca823a98c7b.png)
get merged into a new one holding all the common sources:
![screenshot_2016-07-07_13-38-58](https://cloud.githubusercontent.com/assets/5417642/16652196/29403dac-4449-11e6-8115-16fcb86853b9.png)

**Comment by CasFre** [comment]
Great.
I manually added the Derksen-reference in the meantime, because I did not know the number of the cognate class anymore, only that it had been D before.
You may implement either your restored one or leave mine.

**Comment by runjak** [comment]
Alright - I'll just write a snippet of code that checks if these three citations still need to be added to `5822` and add them only if necessary.

**Comment by runjak** [comment]
I've deployed the corrected merge behaviour and added the missing citations to cognate class `5822`.

**Comment by runjak** [comment]
If I'm not mistaken the only thing left open for this issue is how to handle cognate class ids on merge. Some thoughts from my perspective:
* Even if we retain one of the cognate class ids on merge the others would still be removed leading to possibly broken links.
* If the original problem with changing ids is that links can be broken this would be part of a bigger problem in that there are different parts of the page where deletion is possible, if I'm not mistaken. And currently we don't take care for any of these cases. That is a link like http://www.cobl.info/lexeme/23793/ could be broken in the future. To deal with this we could redefine how deletion currently happens: Instead of removing content from the database we could add a `deletion` timestamp and not display deleted entries per default. I think this problem would warrant a different issue and probably a discussion with it.
* If it's helpful or necessary I could search the database for notes that contain ids or URLs so that it's not too hard to find specific entries that may include broken links.

**Comment by runjak** [comment]
Strategies discussed with @cormacanderson:
* When merging figure out if an id that the merge code wants to delete is used somewhere on the page.
  - See `/cognate/2150/` for an example. Cognate Class Citation notes, Lexeme Notes, etc…
  - Cognate Class Source Id
* If removing an entry would break something we should inform the user and display options on how to proceed.
* When merging classes we could merge into the larger class to circumvent potential problems.

**Comment by PaulHeggarty** [comment]
It seems like this has been left as is for two weeks now.  This suggests that any outstanding problems with it are much less urgent -- perhaps downgrade the urgency?  Could somebody who knows update this issue with the latest info on it, in any case?

**Comment by CasFre** [comment]
I leave that to @runjak or more probably @cormacanderson. Didn't do any mergers recently, only splits.

**Comment by m-scarborough** [comment]
I've found that the new assignments feature on the meanings page works reasonably well for mass-merging, although the references still have to be copied over manually.

**Comment by runjak** [comment]
From my perspective the possible changes listed in my [previous comment](https://github.com/lingdb/CoBL/issues/197#issuecomment-232364479) are only concerned with mitigating potential problems that can arise if some notes contain links to a cognate class. Because merging eliminates a cognate class from the database links to existing cognate classes could break.

* It would be possible to write code that checks the database to see if any such links can be found, but this would take some time to do.
* An alternative would be to say that we either don't care about breaking links in notes for now and that this will be discovered at some time later either by writing/using a link checker at some time or by users stumbling upon it.

If no one is against it I would suggest closing this issue for now and considering the links again if and when they become a problem.

**Comment by PaulHeggarty** [comment]
I agree with Jakob's comment that the issue can be closed for now on these grounds, but the reason for keeping it open would be whether what Matthew says (in his previous comment) is still true.  If merging two classes loses the references from the 'deleted' one, then that still should be fixed urgently, so that users do not have to re-add them manually.  Can you check whether that is now working?  If so, this issue can be closed as you say.  If not, add it as a check box point to do within this issue, and keep it open.

**Comment by runjak** [comment]
Agreed - it makes sense to check that references are copied correctly.
But: I have problems figuring out what the 'references' are that have problems here. @m-scarborough can you point me to it or give me a hint/screenshot here? Is this a problem with the citations again/still? Because I assumed that this was solved [some days ago](https://github.com/lingdb/CoBL/issues/197#issuecomment-231071962).

**Comment by m-scarborough** [comment]
What I meant by that comment is that if you merge two sets through the new selection-assignment tool, the citations in the cognate view have to be copied and re-input into the merged class manually.  I mean the citations at the bottom of this screenshot — that is, if they exist or even continue to the be relevant to the class.

<img width="1208" alt="screen shot 2016-07-29 at 12 08 00" src="https://cloud.githubusercontent.com/assets/15671787/17246639/59d09352-5585-11e6-9232-73f6ff902823.png">

I don't think this is a serious problem and the issue should probably be closed.

**Comment by CasFre** [comment]
I would rather suggest downgrading the issue again to 1th priority, rather than closing it.
The problem with the citations is of course not a vital thing for CoBL as it is primarily used now (I suspect, they don't go into the export... ;-P ), but they will be relevant for scholarly use after the launch and are important for CoBL's reputation.
So I think @runjak should find a solution for that within the next weeks.
My preference would be that they are kept in the merging process, and that one can then afterwards check manually, whether some can be or even have to be dropped after the merger.
From my own experience with mergers, I think it otherwise happens so easily that one merges two cognate classes, closes the individual cognate class pages for them, goes to the new class and then has forgotten what citations where in there. Moreover, manually copying - even with copy and paste - takes some time, as you also have to re-select the source and also copy page numbers. This is something basic which also the new citation system to come cannot get rid off.

**Comment by PaulHeggarty** [comment]
I competely agree with Cassandra, this is still pretty high priority for the reputational reasons, and should not be closed.
Bottom line is that we should *never* waste any expert's time doing things manually that should be done computationally.  If it is true that this is unresolved (?!?) then it must not be closed.  And it  absolutely does need to remain high priority.  I will put it in as 1st, not to distract Jakob from immediate other tasks today, but next week it should be done.

**Comment by runjak** [comment]
Thanks for specifying this for me, @m-scarborough!

**Comment by PaulHeggarty** [comment]
Could anyone tell us whether there is still any problem left with this?  Jakob thinks the merger of references should now be working.
(The only outstanding issue is that links anywhere else in the database to any of the former cognate classes merged in these operations will no longer work, because this merge operation just deletes those classes 
and creates a new merged one.)
