### ISSUE TITLE
non-numeric characters in the “Loan event time depth BP” field

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#202]
Currently, the “Loan event time depth BP” field doesn't allow an input like “>500” (for a loan that took place more than 500 years BP), please make this possible. @runjak

**Comment by runjak** [comment]
If I'm not mistaken these fields are of possible interest for Beast exports. In that case I'm not entirely sure how to progress and would like a second opinion of @PaulHeggarty or @cormacanderson before changing this.

**Comment by nitsnatsnok** [comment]
Citing Cormac:

> I think that the way you tried to do it is correct, and that this should be possible in the database, even if it is not currently. Please put up an issue about this here https://github.com/lingdb/CoBL/issues, assigning runjak (Jakob). It should be pretty easy to fix - just changing the allowed input for that particular field.

**Comment by cormacanderson** [comment]
In the future, they may be of use for the Beast export, it's true, although they will hardly be used in this function for a while. I think the important thing for now is to get the data in, which means allowing more characters, e.g. minimally < and >. If we are going to use this data in Beast, then probably we will have to change these again, but then we would need more detailed calibrations anyway in that instance, similar to what is on the clades table.

**Comment by PaulHeggarty** [comment]
I agree with Cormac. Eventually, a long way down the line, these fields will be replaced by the combination of multiple fields as used for other calibrations. But the re-programming to that end cannot be a priority for now.  If it's quicker just to change this field to text, then do only that for now, Jakob, and we'll sort the rest out at a later stage.  Probably not until September or so.

**Comment by PaulHeggarty** [comment]
Aside to @nitsnatsnok:

When you create issues, please add labels to them.  We have too many issues not to use this.  We all use the labels to filter and prioritise by, and we will miss issues if they're not correctly labelled.

Please add:

*  A **priority rank** label  (0 is highest, to be used only for immediate, very urgent tasks).

*  An **estimated time** needed to complete.

*  An **issue type** label:  e.g. if it's a data issue (like most of yours are) rather than a programming one (like most of Jakob's).  Please also add a label for which database is the one concerned, i.e. in most cases for Aviva, [zData Malakula].

*  An **issue set** label, if necessary in addition to the issue type.  So for example, there's a group of issues that all have to be done for the offline version.  This is very important right now so that Jakob can see what he has to fix for Friday.

Please could you do this already for the existing issues not fully labelled.  Thanks.

**Comment by nitsnatsnok** [comment]
@PaulHeggarty: I am currently not able to add labels or assign people, probably due to a lack of permissions. I informed Cormac about this and will complete “my” issues as soon as I am able to.

**Comment by runjak** [comment]
Thanks for clarifying this - I'll alter the database accordingly :)
