### ISSUE TITLE
meanings in truly alphabetical order

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#203]
Currently, the meanings appear in a strange non-alphabetical order in apparently every list, see for example fight-nail-fire
![2016-06-22-180934_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/16274344/82695f76-38a5-11e6-8c0f-19e6ca363fa4.png)
or the end of the word list, where it gets really messy (here with the “all” meaning list, but “Jena200” to a lesser extent also shows this issue):
![2016-06-22-180956_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/16274426/d598beb2-38a5-11e6-8bd5-111053a9bc85.png)

I suppose this is a problem of the website, but it could as well be a data problem. Jakob, what do you think about that?

**Comment by runjak** [comment]
I agree that alphabetical order is desirable. My hunch is that the current order is just the order that things are listed in the database. The all list has the special function that every meaning will get added to it, and I'd guess that the current order reflects the order of addition of meanings to the database in some way. Alphabetical order should not be hard to do - indeed I have done similar changes in other places already.

**Comment by cormacanderson** [comment]
Yes, what happened here is that a) some meanings were renamed, e.g. `breast` to `chest`, but retain the original ordering, while others were added, i.e. the ones that appear at the bottom. Changing this would be desirable.

**Comment by runjak** [comment]
Is there any case where we'd want the meaning lists to be a different order than alphabetical?
Because the way the code currently does ordering of meanings is by assigning for each meaning in a meaning list an `order` number to order them by.
![screenshot_2016-06-29_11-48-49](https://cloud.githubusercontent.com/assets/5417642/16448018/93c4a2c2-3def-11e6-8f71-0a9e0597bffa.png)
This is essentially the same mechanism used for ordering languages and it's questionable if we need to keep it.

That said I have a fix for this issue, I believe.

**Comment by cormacanderson** [comment]
I can't, at the moment, think of a case in which we need an order other than alphabetical, so if you have a fix, go right ahead :)

**Comment by runjak** [comment]
OK, thanks for clarifying!
This way I can clean up the portion of code
that deals with the `order` fields as we'll always sort meanings alphabetically.

**Comment by evoling** [comment]
The reason the ordering mechanism exists is that Swadesh lists are often presented in semantic order, with similar meanings together. I think database users would still find this useful. I don't see any advantage in removing it.

Michael

On 29/06/16 11:50, "Jakob Runge" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there any case where we'd want the meaning lists to be a different order than alphabetical?
Because the way the code currently does ordering of meanings is by assigning for each meaning in a meaning list an order number to order them by.
[screenshot_2016-06-29_11-48-49]<https://cloud.githubusercontent.com/assets/5417642/16448018/93c4a2c2-3def-11e6-8f71-0a9e0597bffa.png>
This is essentially the same mechanism used for ordering languages and it's questionable if we need to keep it.

That said I have a fix for this issue, I believe.

**Comment by cormacanderson** [comment]
Yes, that's fair enough. It could be useful at times to say, group the numbers together, or body parts, or related meanings like "ash" and "dust", although this is not currently being implemented. At the moment, the ordering is not based on either semantic or albhabetical criteria. @runjak is there a straightforward way to implement alphabetical order then without abandoning the ordering mechanism, leaving the option open for us to implement semantic ordering at a later date?

**Comment by evoling** [comment]
Just set the default order so that it happens to be alphabetical :)

On 29/06/16 12:29, "Cormac Anderson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that's fair enough. It could be useful at times to say, group the numbers together, or body parts, or related meanings like "ash" and "dust", although this is not currently being implemented. At the moment, the ordering is not based on either semantic or albhabetical criteria. @runjak<https://github.com/runjak> is there a straightforward way to implement alphabetical order then without abandoning the ordering mechanism, leaving the option open for us to implement semantic ordering at a later date?

**Comment by runjak** [comment]
Sure - ordering is easy enough to set without removing the `order` column.
I just wanted to make sure we're not keeping something that isn't useful anymore.

**Comment by runjak** [comment]
See 490eae1 for the patch that only makes alphabetical ordering the default.

**Comment by runjak** [comment]
I've deployed the patch and the order of meanings should now be as expected.

**Comment by cormacanderson** [comment]
This is not currently working as desired, specifically for the meanings for which we have changed the English translation, e.g. `chest` not `breast`, `you (sg.)` not `thou`. For this reason, I am reopening this issue.
@runjak could you also please change `dull` to `blunt`.

**Comment by runjak** [comment]
I'm having trouble figuring out which part of the page you're talking about.
When I'm viewing a meaning list it's ordered alphabetical:
![screenshot_2016-07-01_13-26-55](https://cloud.githubusercontent.com/assets/5417642/16520302/88012ac2-3f8f-11e6-9fba-4ff749b03306.png)
![screenshot_2016-07-01_13-26-31](https://cloud.githubusercontent.com/assets/5417642/16520305/8a6af0a4-3f8f-11e6-9fd1-b54b8422a8e3.png)
The same holds for the prev/next links in both `per meaning` views:
![screenshot_2016-07-01_13-28-29](https://cloud.githubusercontent.com/assets/5417642/16520343/cbc06232-3f8f-11e6-8d5f-1837a1ea5d9c.png)
![screenshot_2016-07-01_13-28-42](https://cloud.githubusercontent.com/assets/5417642/16520344/cbc0ef2c-3f8f-11e6-84f2-f4908642a7f2.png)

Also when viewing `http://www.cobl.info/wordlist/all/`
I can find neither `breast` nor `thou` but instead `chest` and `you_sg`.

Lastly when logged in renaming a meaning is as simple as navigating to the meaning list and entering a different `name` - at least on my machine - does this behave differently on the server?

**Comment by cormacanderson** [comment]
What you say is true for the `meanings reference` html form, but not for the `1 lg all mngs` html forms, which are the ones the data entry people will be predominantly using. You are also correct that the meanings are currently defined as `chest` and `you_sg` not as `breast` and `thou`, but on the `1 lg all mngs` html forms, e.g. `chest` is listed as though it began with br-.

**Comment by runjak** [comment]
Good point!
It appears that this specific view did it's own ordering of lexemes in [ielex/views.py:710-716](https://github.com/lingdb/CoBL/blob/047c7bbcedcbfa00ae425b349f65335ed697a30c/ielex/views.py#L710-L716).
From local tests I see that removing this custom sorting results in `meaning_gloss` being used for sorting.
This issue will be closed once the correction is deployed.
