### ISSUE TITLE
Allow underlining in transliteration field

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#204]
In some languages, e.g. Hindi, the standard transliteration includes underlined characters or groups of characters, e.g. underlined kh for /x/ (it appears github doesn't allow underlining either). Insofar as possible we should adhere to standard transliteration practice. Can this be easily implemented?

**Comment by runjak** [comment]
The reason GitHub itself has no u̲n̲d̲e̲r̲l̲i̲n̲e̲ [appears to be rooted](https://programmers.stackexchange.com/a/207730/65877) in the [original design](https://daringfireball.net/projects/markdown/syntax#em) of markdown.
The [underline](https://en.wikipedia.org/wiki/Underline) used for the word `underline` above is the Unicode underline symbol which should be already usable with the database. There is even an [online tool](https://thejh.net/misc/unicode-underline) that aids underlining text.

I'm currently having a bit of trouble with the database on my machine and will test this out to make sure everything works as expected.

**Comment by cormacanderson** [comment]
That's not an ideal solution, unfortunately, as there should be a single underline under "kh", rather than a separate one for each character. The transliteration is of a single character after all, and k̲h̲ suggests two different characters. If there is no solution to this, then we will have to find an alternative. Out of interest, what troubles are you having with the database? It was also acting up for me yesterday and earlier today.

**Comment by runjak** [comment]
With the development changes on my machine changes to the `transliteration` fields wouldn't save correctly. I'm uncertain if this is a general problem or just happening on my machine.

**Comment by runjak** [comment]
Turns out the experienced problem was just local to my development setup because I broke things.

**Comment by runjak** [comment]
I think it would be ideal to have a Unicode solution for this because it would easily be available everywhere. Given that the Unicode underlining is not a solution I would recommend a special field that uses JavaScript to keep track of underlined content. The database representation would become a Unicode string together with tuples of indices that refer underlined content or something similar. The obvious downside would be that such a custom solution would depend on our specific understanding of what underlines are and would me harder to use with other applications. (For example copy&paste wouldn't easily work)

**Comment by runjak** [comment]
One way to realize underscores would be to introduce a custom JavaScript input that encodes underlining with special unicode characters understood by our system.
This would still allow for copy&paste to an extent (except for underlines) and the database would still only store a single string. For the transliteration.
It would perhaps make the most sense to meet up for this and have a small discussion on it in person so that I can be more confident that I understand the problem correctly and that we can figure out a good possible solution together.

**Comment by cormacanderson** [comment]
Agreed, there are more important things than this and I thought it would be more straightforward. We can chat about it the next time we meet and discuss the options. I will downgrade the priority of this issue.

**Comment by runjak** [comment]
Ok, so according to [iam.uni-bonn.de](http://www.iam.uni-bonn.de/~alt/html/unicode_121.html) and [a pdf at unicode.org](http://unicode.org/charts/PDF/U0300.pdf) the interesting unicode codepoints are:
* `U+0331` described as `COMBINING MACRON BELOW` which underlines a single symbol leaving gaps between symbols
* `U+0332` described as `COMBINING LOW LINE` which also underlines a single symbol but the underline is supposed to connect on the sides.

Examples:
* ḵẖ
* k̲h̲

As you may be able to see the appearance of gaps and how clearly you can see them also depends on the font. But the second example is the one that should be chosen if both symbols should be underlined by a single line.
