### ISSUE TITLE
Compute some statistics

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#225]
@cormacanderson asked me to provide some counts for the database.
![20160714_101145](https://cloud.githubusercontent.com/assets/5417642/16835200/dfa6c462-49b7-11e6-8741-5fd493c2b156.png)
It's worth having an issue for this because I want a place to track the code I'm writing for this in case it would be useful again later.

**Comment by runjak** [comment]
Files I've generated from above task description:

Filename | Count(Lexeme ids) | Description
-------- | ----------------- | -----------
   [1.txt](https://github.com/lingdb/CoBL/files/363504/1.txt) |               154 | + lex. ecl. - Not swh
   [2.txt](https://github.com/lingdb/CoBL/files/363505/2.txt) |                 1 | + lex. loan - Not swh
   [3.txt](https://github.com/lingdb/CoBL/files/363508/3.txt) |                 1 | + lex. loan
   [4.txt](https://github.com/lingdb/CoBL/files/363506/4.txt) |               305 | + `count(cognate sets) >= 2` - Not swh
   [5.txt](https://github.com/lingdb/CoBL/files/363503/5.txt) |              1182 | + cog. excl.
   [6.txt](https://github.com/lingdb/CoBL/files/363507/6.txt) |              1510 | + cog. loan

-----

Now assigning this to @cormacanderson to use as he pleases.

**Comment by cormacanderson** [comment]
Thanks for this @runjak. I've just realised I've forgotten some things. Firstly, are these counts based on the meanings in the `Jena 200` or in the `all` list? Secondly, could you run the + cog. excl. and the +cog. loan again, filtering only -Not Swh meanings?

**Comment by runjak** [comment]
Sure thing - I'll do that :)
The current data is based on the `all` list - I'll make sure to change this.

**Comment by cormacanderson** [comment]
Thanks @runjak. A further question. Which language list are these figures based on?

**Comment by runjak** [comment]
Ah - stupid me - this is on the basis of the `All` list, I believe - presumably I should have based this on `Current` instead?

**Comment by cormacanderson** [comment]
Hi again. It should be based on the `Current` list, yes, but it's not your fault. I should have been explicit about the lists. Is it very time-consuming to run it again?

**Comment by runjak** [comment]
No - shouldn't be taking too long - I'll be right on it!

**Comment by cormacanderson** [comment]
Great! Thanks a million.

**Comment by runjak** [comment]
Here's the updated data for the `Jena200` and `Current` list:

Filename | Count(Lexeme ids) | Description
-------- | ----------------- | -----------
   [1.txt](https://github.com/lingdb/CoBL/files/366131/1.txt) |                32 | + lex. excl - Not swh
   2.txt |                 0 | + lex. loan - Not swh
   3.txt |                 0 | + lex. loan
   [4.txt](https://github.com/lingdb/CoBL/files/366130/4.txt) |               136 | + `count(cognate sets) >= 2` - Not swh
   [5.txt](https://github.com/lingdb/CoBL/files/366132/5.txt) |                44 | + cog. excl. - Not swh
   [6.txt](https://github.com/lingdb/CoBL/files/366133/6.txt) |              1043 | + cog. loan - Not swh

**Comment by cormacanderson** [comment]
Great! Thanks a million for that.

**Comment by runjak** [comment]
You're welcome!
Thankfully I didn't throw out the statistics code after the first computations so now repeating this exercise would not have too big time costs.

Also in retrospective: I could have anticipated the lists

**Comment by cormacanderson** [comment]
@runjak I think there is something of a problem with the "cog excl.", because there are lexemes in the list (file 5) which are not marked as excluded in the cognate judgement of these lexemes. However, the ARE marked as excluded in the lexical judgement.
Furthermore, it appears that all lexemes marked as "excluded" in the lexical judgement are also marked as excluded in the cognate judgement. I have checked the lexemes in the screenshot below and can confirm that they are not "excluded" in the cognate judgement section (in fact I removed their exclusion there myself and moved it to the lexical judgement). 
![screen shot 2016-07-16 at 13 40 42](https://cloud.githubusercontent.com/assets/8975419/16894587/26cd8da4-4b5b-11e6-95e5-ca76d3d7b4df.png)
I wonder on this basis if there is an error in how `Cog. excl.` is being calculated. This box should only be marked if a lexeme is marked as excluded in the cognate judgement, not the lexical judgement. At the moment it looks like you're calculating it on the basis of both cognate and lexical judgements.

**Comment by runjak** [comment]
Embedding some screenshots from [models.py](https://github.com/lingdb/CoBL/blob/022bacbc21edb1f5a5c288d16780b16e55f0ee2d/ielex/lexicon/models.py) to illustrate the search for the problem:

The [code](https://github.com/lingdb/CoBL/blob/%23225/ielex/lexicon/migrations/0086_issue_225.py) for searching for the wanted lexemes looks like this:
![screenshot_2016-07-18_12-02-35](https://cloud.githubusercontent.com/assets/5417642/16911620/d5ffd8a6-4cdf-11e6-9ae1-b65715029050.png)
![screenshot_2016-07-18_12-02-06](https://cloud.githubusercontent.com/assets/5417642/16911626/dc012b60-4cdf-11e6-84b1-cb71e017a2d8.png)
This is basically iterating through all lexemes we're interested in and checking whether `not not_swadesh_term` implies `is_excluded_cognate`.

The `is_excluded_cognate` attribute of a `Lexeme` is computed like this:
![screenshot_2016-07-18_12-00-21](https://cloud.githubusercontent.com/assets/5417642/16911859/38866db8-4ce1-11e6-8535-869d6d244381.png)
So a lexeme reports that it is excluded via `CognateJudgement` iff any of its judgments is marked as excluded.

A `CognateJudgement` finally is marked like this:
![screenshot_2016-07-18_11-59-59](https://cloud.githubusercontent.com/assets/5417642/16911887/61efb484-4ce1-11e6-9ced-0ff0dbf47957.png)

So I'd say that your deduction was right here - it appears that the `CognateJudgement` for some reason also looks at the `Lexemes` reliability when asking the question whether or not it is excluded. I'll fix this and run the computation again, but I'll also see where this information is currently used in other places to see if something else could break.

**Comment by runjak** [comment]
Here is an updated version of the file: [5.txt](https://github.com/lingdb/CoBL/files/368753/5.txt)
It's now reduced to 26 entries.

**Comment by PaulHeggarty** [comment]
I think the most urgent things here have already been done, and Cormac is away for now in any case, so I’m down-rating the urgency level.

**Comment by cormacanderson** [comment]
@runjak , I would like you to compute two further sets of statistics:

1) Lexemes which are marked as "Loanword" in the reliability judgement for [Cognate citation], but are affiliated to a cognate class which is not marked "Loan Event"

This will filter out any cases which Konstantin may have missed in https://github.com/lingdb/CoBL/issues/228, or which may have been added since he completed this task.

2) Lexemes which are marked as "Loanword" in the [Cognate judgement], but which are unaffiliated to any cognate class.

This will pick up any stray lexemes which have not been assigned to any cognate class.


Also, note that currently, "Cog. Loan" is NOT being marked in the correct checkbox on the `1 Mng All Lgs` form for lexemes which are marked as loanwords in the reliability judgement for `Cognate citation`. See here:
![screen shot 2016-08-01 at 19 32 46](https://cloud.githubusercontent.com/assets/8975419/17302943/c801aab4-581e-11e6-87c9-5af20a23f0ec.png)
Going to the individual cognate sets, we see that these lexemes are still marked as loanwords in the reliability judgements:
![screen shot 2016-08-01 at 19 31 49](https://cloud.githubusercontent.com/assets/8975419/17302953/e1f60118-581e-11e6-83b3-0d48b91c2eec.png)

**Comment by runjak** [comment]
Ok, I've gathered some statistics on this.
1. I found `44` cases for the first task: [1.txt](https://github.com/lingdb/CoBL/files/396369/1.txt)
2. But so far no cases for the second task. I'll double check that the computation is correct for this one.
