### ISSUE TITLE
Editing cognate set [Root Language] and [Root Ref. Form] fields

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#241]
Among some significant changes yesterday 2016-07-26, it was decided to lock — i.e. make only viewable, not editable — the root form and root language fields within the [1-Language, All Meanings] form.  

The logic was that the ability to do this was useful in the early stages, when we had experts like Matthew filling these fields in directly from individual languages like Greek, where many of the forms were immediately known as reflexes of known Proto-Indo European cognates sets.  But now that most of those ‘easy’ cases have been done from the main individual ancient reference languages (or at least the main European ones?) we now face instead the danger of people working on an individual modern language, who might blithely fill in what look like blanks, only as relevant to an etymology in their language within their branch only.  So to head that off, we have switched off editing these fields from [1-Language, All Meanings] view.  

The question for all of you now, however, is what to do about the [1-Meaning, All Languages] view.  Yesterday, we switched off editing these fields there too, so that they can only now be edited in the [1-Meaning, All Cognate Sets] form.  I’m now not so sure this is the best solution, because that form does not show which individual languages have a lexeme from a given cognate set, so checking needs multiple clicks.  

So on second thoughts, I think the [1-Meaning, All Languages] form is a good place for these fields to be editable.  This can be done especially in combination with the new function, already implemented I now see, to ‘filter by cognate set’ on this form, so that just typing the Cognate Set Alias letter show all and only languages whose lexemes are assigned to, say, cognate class C.  

What are your thoughts?

**Comment by CasFre** [comment]
Thank you for putting this under discussion, @PaulHeggarty.
I guess there are different working styles or different possible perspectives on this problem.
**Possible Solution A.** So maybe a handy solution would be rather to keep the editability in all forms, but to create a new type of user such as "cognacy coder" or something and to allow only these people to edit the entries anywhere. So everybody would have maximum convenience, no matter what perspective he/she currently has. - I say introduce a new type of user, because, in the long-term view, I would not tie these rights directly to admin-status, because admin rights pertain to database administration in general, which is a separate issue and a different kind of responsibility.
**Possible Solution B.** Otherwise, I would maybe suggest rather a re-design of the 1 mean - all cognate sets and the individual cognate sets pages or at least an implementation of editable root form and root language fields on the individual cognate set page. Because I think that also those trained people that we allow to change root forms should be prevented from merely filling in root forms without considering the overall picture concerning that particular cognate class. And this is at the moment best provided on the individual cognate set page, because one also finds the citations and full text of the notes there. If somebody fills in a root form or changes it, then he/she should also add some reference in most cases, or be aware of the fact that references must also be updated afterwards.
So in order to ensure accuracy of the data, I would maybe even prefer solution B. The only objection I might see to it is: What about the lexemes marked as excluded? They are currently not shown on the individual cognate set page, but only on the 1 mean - all lang page, right? And on the 1 mean - all lang page of course only if one sets the respective filter in such a way that they are displayed, which people might also tend to forget. - Opinions on that?

**Comment by runjak** [comment]
I've implemented code that makes the `Root ref. form` and `Root ref. language` columns editable in `1 meaning all languages` view.
Since the same cognate set can be mentioned in that view several times the server will only change these entries once. Please have a look at [#278](https://github.com/lingdb/CoBL/issues/278#issuecomment-238583556) for a more detailed description of this behaviour.

**Comment by runjak** [comment]
#278 is deployed and the `Root ref. form` and `Root ref. language` columns are edtiable in `1 meaning all languages` view again.
