### ISSUE TITLE
How to treat references to older handbooks

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#258]
At the moment, references to Walde-Pokorny, Pokorny's IEW or Buck figure prominently in the Notes fields of many cognate sets. Often the exact form of their reconstruction does not live up to modern standards any more. However, these references are of course useful in order to trace research history and in some cases, they might actually be necessary to consider because of their broader approaches (IEW: not only verbs or nouns, but both; Buck: semantic approach as in CoBL as it stands).
So maybe a good solution would be to move these quotations from the notes-fields into corresponding citations. This might then something to share between the individual cognate coder of a cognate class and @nitsnatsnok who could go through that, then maybe also checking the actuality of links between cognate sets.
Comments?

**Comment by PaulHeggarty** [comment]
I agree, but we're moving to a new system for citing sources in a week or two.  And citations are currently not contributing much to the urgent goal of getting a data set as good as possible for the next export on 20th August.  So this does not seem to be a priority at the moment.  Yes, it is a priority for 'public consumption' when the database goes live, but that certainly cannot happen soon, and will happen only well after the basic data -- i.e. cognate set assignments -- are complete and sound in any case.  To that end, what we need is the cross-checking of the accuracy of cognate sets, splitting and merging where necessary, and identifying root forms and root languages so that individual language specialists who are not Indo-European specialists can more accurately assign cognacy.  So please do not spend time on revising old citations for now.

**Comment by m-scarborough** [comment]
Almost all the references to Walde-Pokorny and Pokorny IEW in notes fields of cognate classes are holdovers from the data entry in IELex 1.  @BrittaIrslinger and I both strongly agreed last October that this stuff needs to be cleaned up if the database is going to be taken seriously.  But yes, not the immediate priority.

**Comment by nitsnatsnok** [comment]
I opened #332 to deal with deprecated references as well as references in note fields, so I'm closing here.

**Comment by m-scarborough** [comment]
So far my working practice has been to delete references to Walde(-Pokorny) (1930) as I come across them while revising cognate sets, although a more systematic cleanup is needed.
