### ISSUE TITLE
Shut down reliability judgements for cognate class citations

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#262]
doh!
![2016-08-04-195833_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/17413655/5e61d082-5a82-11e6-9f2d-d1b374fc000a.png)

**Comment by cormacanderson** [comment]
Okay, we proceed then as in the other cases. @runjak, could you give us statistics for how many instances of  `cognate class citation` are 1) doubtful, 2) loanword, and 3) excluded. Hopefully there are not too many of them. Then Konstantin can check them, then we set them all to "high", then we turn off citations for `cognate class citation`.
- [ ] Provide statistics for reliability judgements for `cognate class citation`
- [ ] Check all instances in which reliability judgements are not "high" or "good"
- [ ] Change all reliability judgements for `cognate class citation` to "high"
- [ ] Turn off reliability judgements for `cognate class citation`

It should be said however, that this is not a Oth priority issue, as these citations are (I presume) irrelevant to the export. To be on the safe side, we should deal with this before we do the export however. I am reassigning to 1st priority for now - something to do when you have half an hour free at some stage @runjak  (presuming it won't take longer).

**Comment by runjak** [comment]
I've been computing the required statistics and found that there are no cases for any of the 3 tasks if I restrict cognate classes to ones that contain lexemes that are:
* `not_swadesh_term=False`
* on the `Jena200` meaning list
* on the `Current` language list
There are cases outside of this selection that I can easily give you if wanted.
Otherwise we could just go ahead with this issue by changing reliability to `High` in all cases on our lists and shutting down reliability ratings for `CognateJudgementCitations`.

**Comment by runjak** [comment]
@cormacanderson I'm uncertain about the statistics here:
* I would compute them again and then close this issue.
* I expect that nothing much will have changed - but the question remains what to do with entries that are outside of our scope - say `not_swadesh_term=True` or not on the `Jena200` list or not on the `Current` language list. Should I set the reliability of these entries to something or just ignore them?

**Comment by runjak** [comment]
Closing this because it appears that there is nothing left to do.
