### ISSUE TITLE
Celtic clade filter is broken

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#266]
With the Celtic clade filter switched on, still no Celtic languages show.  In both `Languages Reference` form and `1-Meaning, All Languages`.
![screenshot - 2016-08-05 13_20_32](https://cloud.githubusercontent.com/assets/8819910/17435248/dd8192c0-5b0f-11e6-8285-86e35623913a.png)
![screenshot - 2016-08-05 13_21_53](https://cloud.githubusercontent.com/assets/8819910/17435250/df2855a0-5b0f-11e6-8877-032c751c8bbc.png)

**Comment by PaulHeggarty** [comment]
Associated to this is in fact a problem we/you must fix, Cormac.  There is an inconsistency in our Celtic clade structure, in that Gaulish is entered without a specific clade.  That is wrong.  We need to assign it to some other sub-clade of Celtic.  We could just call it 9, Other.  Something is amiss here, I feel.  Celtic is the only case where this happens.

**Comment by cormacanderson** [comment]
I have fixed the Gaulish issue by assigning it to a clade Continental. This may or may not be a valid clade, but seeing as Gaulish is the only Continental Celtic language in the database, it is not likely to cause issues at this point, and the terminology is well accepted.
This did not solve the filtering problem. Could this be due to the fact that Celtic, uniquely among the clades, has a clade 0 designation with two figures?

**Comment by runjak** [comment]
Found the problem for this one.
Issue will be closed on deployment.
