### ISSUE TITLE
Not Swh filtering not working on [1-Mng, All Cog Sets] form

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/CoBL#273]
The Not Swh filtering does not seem to be working on the `1 Mng, All Cog Sets` form. In the screenshot below, cognate sets `2568` and `3904` both have a single lexeme, which has been marked as "Not Swh", but only one of them shows up as "Not Swh" in this view, and is excluded. 

![screen shot 2016-08-07 at 15 21 06](https://cloud.githubusercontent.com/assets/8975419/17462608/9e33519a-5cb2-11e6-8fd7-a7e076d40171.png)

Worse is the following meaning, where in the four bottom cognate sets all lexemes are marked "Not Swh", but still they appear in this view.
![screen shot 2016-08-07 at 15 26 47](https://cloud.githubusercontent.com/assets/8975419/17462638/977649b0-5cb3-11e6-9719-09adecc2389d.png)

**Comment by cormacanderson** [comment]
Note that the `Clade count` for these meanings indeed appears as zero.

**Comment by PaulHeggarty** [comment]
I think that last observation could be the whodunnit clue that points to the solutionThat the `Clade count` appears as zero suggests a way of tackling this, because it implies that the filter IS working correctly on the `Clade count`!  So check how that was achieved and try to apply it to the `Lex. Count` too.  Looking at the differences in sources/filtering between those lists should reveal the difference, some filtering out of Not Swh lexemes that is being correctly applied to the `Clade count`, but missing or wrong in the SQL for the `Lex. count`.

**Comment by PaulHeggarty** [comment]
This is so similar to the remaining problem still in #236 that I hope the bug/solution will be the same.

**Comment by runjak** [comment]
The problem here appears to be the way that I'm calculating the lexemes of a cognate set.
I'm falsely considering all lexemes in [models.py:837](https://github.com/lingdb/CoBL/blob/465ecb0e60878d25725323b02cc8611e846c221a/ielex/lexicon/models.py#L837) where I should instead only consider the ones in the current lists.
* Fortunately this is something easy to fix.
* Unfortunately this is a common mistake in various parts of the code.

When viewing the all lists we can see that cognate set `2568` has a second entry:
![screenshot_2016-08-08_13-33-37](https://cloud.githubusercontent.com/assets/5417642/17478525/cedd4746-5d6c-11e6-8509-8217fef722dd.png)

**Comment by runjak** [comment]
I've written code to improve the offending code.
As a result the `Not swh.` fields behave better:
![screenshot_2016-08-08_13-38-02](https://cloud.githubusercontent.com/assets/5417642/17478642/9a631cc4-5d6d-11e6-826f-02cb19fdaa58.png)
![screenshot_2016-08-08_13-38-46](https://cloud.githubusercontent.com/assets/5417642/17478641/9a61dcc4-5d6d-11e6-9473-91d7a0888ad4.png)
