### ISSUE TITLE
Meaning EAT not available on [1 Meaning, All Languages] html form

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/CoBL#289]
It's letting me pull up all other meanings in all Germanic languages, but not EAT for some reason.

**Comment by cormacanderson** [comment]
It's not working for me either, although the `1 Mng, all cog sets` form is available. Bit bizarre this one.

**Comment by runjak** [comment]
Found the bug for this one.
Will soon deploy a patch.

**Comment by runjak** [comment]
The problem was my assertion for the `Root ref. form` and `Root ref. language` columns to be always relating to `0` or `1` cognate class, but never for more. This is not the case for Icelandic:
![screenshot_2016-08-11_09-09-19](https://cloud.githubusercontent.com/assets/5417642/17581015/4c455498-5fa3-11e6-9679-962e89bb5485.png)

The workaround will be to not make the `Root ref. form` and `Root ref. language` columns editable in this case because it would not be clear which cognate set to change.
