### ISSUE TITLE
cognate class 3891 and cognate class 2467

### ISSUE THREAD

**Issue by RolandPooth** [lingdb/CoBL#290]
I found Kashmiri YED 'belly' - which has two Id 25070 and 25069 numbers - in these two cognate classes ... A mistake?

**Comment by cormacanderson** [comment]
The lexeme was entered twice in the language data. I deleted the second occurrence and cognate set 3891 (of which it was the only member).

**Comment by cormacanderson** [comment]
For future reference @RolandPooth, it's a good idea to assign someone  (me of @CasFre in this instance) to an issue like this, so that we see it instantly. Otherwise, there's the risk you have to wait a while until someone notices it. You can do this on the menu bar on the right, and also give it a label, so that we can find it again, and if you want you can also a priority assignment.
