### ISSUE TITLE
Deadline 26th August 2016

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#302]
Hello @cormacanderson and @PaulHeggarty,

as a side-effect of my latest call with Roland, the following questions arose:

1. Is there already a certain time-point on which you are planning to do the export on Friday, e.g. 12 am, timezone xy or the like? - Regarding the overall time pressure, we should be clear about that.

2. Should people stop working by then? Roland feared that data which he enters while the export is being done might get lost.

**Comment by cormacanderson** [comment]
It all depends on how fast we can get through the nexus export issues, so I'm afraid we can't predict it. I imagine that it will be Friday evening rather than morning certainly. Obviously, we can hold off a little bit if there are five cognate sets left to be coded, or whatever. I don't think data will be lost in the way Roland is worried about, but I'll ask Jakob about it anyway. Once things are clearer and we have a better idea about when exactly we will be doing the export, we can plan a little better. As soon as I know more, I'll tell you.

**Comment by runjak** [comment]
Closing this issue as the deadline has passed.
