### ISSUE TITLE
Add copy button to twoLanguages view

### ISSUE THREAD

**Issue by runjak** [lingdb/CoBL#312]
We still want a `copy over` button for the `twoLanguages` view.
This was originally described in #256 like this:

> Ideally, there would also be one new button in this 2-Languages, All Meanings form, only to appear on the records for the Target (not the reference) language, which would just be 'Copy over cognate class assignment from Reference language'. That would be its tooltip, and it should do what that says.

**Comment by runjak** [comment]
I've implemented the requested copy button.
![screenshot_2016-11-17_14-48-07](https://cloud.githubusercontent.com/assets/5417642/20391774/19960932-acd5-11e6-9afc-97f6a79fac1c.png)
It will fill in all empty text inputs of a row copying the data over from the original row.
In the case that no original exists the button won't appear.
In the case that two rows exist for one meaning but only one original only one row will have the button.

This issue will be closed automagically on deployment.

**Comment by PaulHeggarty** [comment]
Ouch, looks like a big misunderstanding here.  There are several problems with this function, and with this 2-language view.  Please revert this deployment back to the previous state, while these are fixed.

Basically, the function implemented is not the right one.  The idea is absolutely *not* copy over **all** empty text fields from the 'original' row.  It is to copy over **only** the cognate set assignment value, i.e. the value in the `Cog. ID` field only. 

- [ ] The arrow should appear not near the start of the row, but only immediately in front of the `Cog ID` column.
- [ ] Clicking the arrow should copy over **only** the cognate set assignment value, i.e. the number value in the `Cog. ID` field only.  (This should then refresh the `Cog. alias` too, automatically.
- [ ] The tooltip for the arrow button needs to be changed too.  It should be:  'Copy over cognate set assignment from the reference language selected here (in grey)'.

Other important changes needed:
- [ ] In the headers, the selected 'reference' language (i.e. the source to cognate assignment values from), in grey, appears correctly below the 'target' language (to copy cognate assignement values to), in white.  But in the table itself, the order is reversed, 'reference' language in grey first, for any one meaning.  Please correct that to put the reference language second, as in the headers.
- [ ] The grey background for the reference language is too dark.  Please use a ligher shade of grey.
- [ ] The meaning name (e.g. 'ash') is in lower case in the reference language, but upper case in the source language.  Please set it to upper case in both.
- [ ] I agree that things were not clear enough, including the headers, so it needs to be made clearer what's going on here.  In the first language row, precede the language name cell with:  `Target lg.:` and the second language name cell with `Source Reference lg.:`.
- [ ] The 2-language view currently defaults to Ancient Greek as target language (which is OK), and Proto-Indo European as source reference language, which is not good.  If possible, please default to no second language selected, and a placeholder text instead of its name, saying: `Type here to select language 2.`  This value should then be remembered for that user.  So should the value for the target language, as soon as that user changes it.
 
![screenshot - 2016-11-17 15_40_43](https://cloud.githubusercontent.com/assets/8819910/20393450/483397da-acdc-11e6-84fd-ea49ddb7a3c9.png)

**Comment by runjak** [comment]
Copying of the cognate class assignments will be done via the alias fields.
There are two possibilities here:
1. Replace the current alias entry with the one from the original.
2. Expand the current alias entry with the one from the original.

I'll go with replace for now as it's the simpler one, but perhaps you want the other @PaulHeggarty?

**Comment by runjak** [comment]
…also with the current way that this is implemented the table would still need to be saved after copying data over.
The alternatives would be:
1. Have the complete table reload for every single copy operation
2. Invest more work to have the copy operation run in the background and fetch the changed data on the fly (I guess that this would take about two days longer).

**Comment by PaulHeggarty** [comment]
See my updates to your above comments in response to your questions.

**Comment by PaulHeggarty** [comment]
One more thing:  
- [ ] For this view, I don’t think we need the previous and next language links in the header rows.  It would be clearer if they were removed and replaced by the `Target Lg.` and `Source Reference Lg.` labels asked for above.

**Comment by runjak** [comment]
Alright - getting rid of the prev/next links should free up some space that should help me with the description texts.

**Comment by PaulHeggarty** [comment]
Since the `Alias letter` will always be in principle less 'reliable' than the cognate set ID number itself, the copy function here should be based on copying the cognate set ID number, not the alias letter.  The alias letter should automatically come with it, of course, like the other looked up data that accompany each cognate set, because they should in any case all be looked up from the ID number.  

It should certainly not be the other way around, i.e. this function should not just copy the Alias letter, and look up the cognate set number from that.  As an illustration of why this is dangerous, see #352 and #141.

**Comment by runjak** [comment]
Yes, I agree with your remark. I estimate that it should be possible to solve this on issue on Monday given that #205 progresses OK.

**Comment by PaulHeggarty** [comment]
It looks like almost everything (all but one of the requested tweaks) have already been fixed here, but it has not been deployed yet.  We want to demo this at the workshop today, if possible, so could you deploy what is already done, at least, and perhaps prioritise the last remaining check box above so that this system will full work, and the issue can be closed?  Thanks.

**Comment by runjak** [comment]
There is currently some [commit history](https://github.com/lingdb/CoBL/network) to clean up, that I need to chew trough before data is ordered so that a deployment can go life safely.
Nonetheless I'm aiming to get this life asap.

**Comment by runjak** [comment]
The remaining part of this issue will be handled in #356.
Since the biggest part of this is solved and the discussion is quite long already it makes sense to start with a clean slate for the remaining part.
