### ISSUE TITLE
New fields/columns in meanings reference table/form

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#313]
- [x] Add a 'meaning specification tooltip' text field, which should appear over the meaning name in the main table views like `1-Language, All Meanings`.
- [x] Add an 'Elicitation Ix' field, numerical (integer up to about 1000) which should also appear in the `1-Language, All Meanings` form, as a column that the records can be sorted by.
- [x] Rename `Elicitation Ix` field to `MeaningSetMember` and introduce an additional `MeaningSetIx` field.
- [x] We may need to add further fields to group meanings into meaning subsets -- to discuss.

**Comment by runjak** [comment]
* I've got an implementation for the tooltips that also displays the tooltips in places where we've got the meanings displayed in other views.
* I've also added the `Elicitation Ix` field, but I'm uncertain how useful it will be. The situation is as follows:
  * We've got filters and sorting in the tables already.
  * These filters and sorting inputs are now remembered for the browser session.
  * This means that we would either need to add the `Elicitation Ix` to the table so that a user could sort by it. Or we could only use it to sort by initially but have it overwritten once the user uses the other sort options.

**Comment by runjak** [comment]
Discussion with @PaulHeggarty revealed that we'll also need columns for `Elicitation Ix` in tables that are sorted by it.
