### ISSUE TITLE
Cross-check question on export logic

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#320]
Jakob, can you confirm our presumption that no cognate set is exported to the nexus file if it is not found in any of the languages in that export?  It should be so, but better to have absolute confirmation, and if possible to see the lines of the export code that demonstrate this!

**Comment by runjak** [comment]
Yes, I can give a description of how the cognate sets are implicated in the export procedure:

First to locate the source for this task: it can be found in [ielex/lexicon/views.py](https://github.com/lingdb/CoBL/blob/c6b7cc6b24d7d8c72cd21144e82d27e428024154/ielex/lexicon/views.py).

In line [166](https://github.com/lingdb/CoBL/blob/c6b7cc6b24d7d8c72cd21144e82d27e428024154/ielex/lexicon/views.py#L166-L169) the `write_nexus` function is defined. It takes care of generating export data from the given list of parameters.

In line [208](https://github.com/lingdb/CoBL/blob/c6b7cc6b24d7d8c72cd21144e82d27e428024154/ielex/lexicon/views.py#L208-L209) we can see that the `cognate_class_names` that will be used in the export are given by the `construct_matrix` function. Up to this point the only data considered are:
* The given `LanguageList` to use.
* The given `MeaningList` to use.
* The `Language`s from the given `LanguageList`.
* The `Meaning`s from the given `MeaningList`.

Lines [379-400](https://github.com/lingdb/CoBL/blob/c6b7cc6b24d7d8c72cd21144e82d27e428024154/ielex/lexicon/views.py#L379-L400) filter the `CognateJudgement`s that will be used in the below code. These judgements are always restricted to the given languages and meanings. Depending on additional options judgements can be excluded for being marked as `PllDerivation,Ideophonic,…`.

A second occurence where cognate data is fetched from the database is in line [434](https://github.com/lingdb/CoBL/blob/c6b7cc6b24d7d8c72cd21144e82d27e428024154/ielex/lexicon/views.py#L434). Here judgements are fetched that belong to a cognate class seen as a result of the prior filtering. They are also restricted to meanings that have already been given.

-----

From this I feel fairly certain that we should not have cognate sets in the export that are not linked to either a language or a meaning that belongs to one of the given lists.

If we need further confirmation of this I can also write a test for this. This would be a small program that computes several exports. It would then use the exports to search for cognate sets that exist in the database and should not be in the export. Such a test would also have the benefit that it would allow us to make sure that no such problem is introduced in the future because we could run it before deployments.

**Comment by runjak** [comment]
Closing this as there is nothing left to do.
Please reopen if further discussion is necessary.
