### ISSUE TITLE
branch colour boxes don't appear reliable

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#330]
[cognate/952](http://cobl.info/cognate/952/) includes greek lexemes, but in [meaning/wash/cognateclasslist](http://cobl.info/meaning/wash/cognateclasslist/) this cognate class appears without the “Hellenic” colour box.
I mark this issue with 0th priority as we need to rely on the system when working on #321.

**Comment by cormacanderson** [comment]
The reason for this is that the Greeek lexemes in that cognate set are marked "Not Swh". The branch colouring on the `1 meaning, all cognate sets` html form is sensitive to the "Not Swh" parameter, but "Not Swh" lexemes still show up in the cognate set report in order to facilitate identification of the root reference form and language.

**Comment by nitsnatsnok** [comment]
It's not a bug, it's a feature then – thanks for clarifying!
