### ISSUE TITLE
Save Button on Language List not working

### ISSUE THREAD

**Issue by nitsnatsnok** [lingdb/CoBL#342]
Adding information seems to be impossible on the [language list](http://cobl.info/languagelist/Current/): After a click on “Save” it loads for minutes eating up lots of space and CPU and crashes eventually. I tried cleaning the cache and restarting the browser (Chromium 53.0.2785.143 on Ubuntu 16.04) without avail.
![2016-11-05-134611_1366x768_scrot](https://cloud.githubusercontent.com/assets/2664162/20030126/d173bc14-a35e-11e6-809c-b9027e4fdcb2.png)

**Comment by leszekjocz** [comment]
I can not also save any changes in the one-meanings-all-cognate-sets view.
![abcd](https://cloud.githubusercontent.com/assets/16056017/20030775/307a6124-a36c-11e6-8a64-669194abae74.png)

**Comment by nitsnatsnok** [comment]
As this affects the work of many to a great extent: 0th.

**Comment by nitsnatsnok** [comment]
The same behaviour in the one-language-all-meanings view – is this a general problem?

**Comment by runjak** [comment]
Likely something that broke during the last deployment.
I'll see to fix this asap.

**Comment by runjak** [comment]
It appears that this is a problem I introduced in 9c03e02b61fe40890cc8e1cf36570344a0e3bec4.

The problem is that until now some timestamps have been handled with timezone data and some without. This leads to inabillities comparing their time differences.
As we use timestamps to check wether a field has changed in between when someone tries to edit it, this breaks editing.

I've developed a fix that I'll test for a bit, but will deploy soon.
