### ISSUE TITLE
The same alias given to two cognate classes.

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/CoBL#352]
By coding a variety for cognacy I got an error using the alias 'E' in the meaning 'big' (something like 'server doesn't understand the entry'). When I took a look at the classes I realized that two separate classes have 'E' as alias. See the attached screenshot.

![e](https://cloud.githubusercontent.com/assets/16056017/20456049/d8a4a076-ae6b-11e6-9bd2-f8f91ccc294c.png)

I could code my lexeme only using the ID.

**Comment by cormacanderson** [comment]
Well spotted @leszekjocz. It appears the same for me, also on the one meaning all languages page. When I try to assign set E to a lexeme, an error message results. @runjak have you any idea what might be causing this?

**Comment by cormacanderson** [comment]
cf https://github.com/lingdb/CoBL/issues/141

**Comment by PaulHeggarty** [comment]
This suggests also that the `Alias letter` will always be less reliable than the cognate set ID number itself, so #312  should be based on copying the cognate set ID number, rather than the alias letter (which should be looked up from the ID number, not the other way around).

**Comment by runjak** [comment]
Yes. This is well known behavior to me.
I've always tried to communicate the limitations of the current `alias` system
So sorry if this comes at a surprise.
This was especially annoying when building the cognate class assignment feature.

The `alias` is only ever computed on the basis of a single meaning.
This means that for a single language and for all cognate classes that belong to a meaning the `alias` may have duplicates.

A special case of this would would be cognate class `647 E`.
It is linked to smoke mostly, but also has a link to big.
I would expect that this cognate class could change it's `alias` depending on which meaning has the most recent update to it's cognate judgements.

A solution to this problem would be to rename all cognate classes at once so that they have an alphanumeric name based on their id only.
This wouldn't be too hard to do, and would have the upside that we would have a `1:1` relationship between an `alias` and the `id` of a cognate class.
The downside of this approach would be that the `alias` names would be longer.

Using our current number of `7139` cognate classes in the database and `26` symbols in the alphabet we use for the `alias` I expect that we need at least `3` symbols in a row for enumeration because `10*26^2 + 14*26^1 + 15*26^0 = 7139`.

**Comment by PaulHeggarty** [comment]
Wow, checking up on the example cognate class you mention here, this is very weird.  

![screenshot - 2016-11-20 23_52_10](https://cloud.githubusercontent.com/assets/8819910/20466945/c1da3ee8-af7c-11e6-8c83-08a71d455f12.png)

I think it's just a bug, I don’t know how this could have been entered, even.  I think we need to check for all cases like this and exclude them.  I’m my understanding of the database, this should not be possible.  We even had discussions saying that it's a shame that some cognate sets are actually duplicated because they appear in different meanings, but we presumed that was a necessary part of the structure used here, also for assigning aliases.   
Whatever, in the data in the screenshot, I consider the entry for 'big' to be a bug, pure and simple.  I’d like to know how it was possible that it got in there, and indeed can stay in there!

**Comment by PaulHeggarty** [comment]
This is definitely a bug, in the data and in a sense in the database, for allowing it.  It is damaging because it is screwing up the counts of which branches a cognate set is found in, see this:  
![screenshot - 2016-11-21 00_00_35](https://cloud.githubusercontent.com/assets/8819910/20466996/c35eb4fa-af7d-11e6-8df0-1bf2c5b00b7f.png)
Here, for the meaning 'big', the false cognate set 647 E is ranked third, since it has reflexes in three branches, but in fact it means 'smoke' not 'big' in two of those, because only in English is it mistakenly entered as a cognate set for big.
I suppose this could have come in from the original bad IELex data, but I wonder if it would be possible still to get this by some fat finger error?  What we need is a validation check when assigning a lexeme to a cognate set:  it should not be possible to enter any cognate set (irrespective of meaning) by just typing in its Cog. ID into the cell for that.  It should only be possible to enter the Cog. IDs of one of the cognate sets for that meaning.

**Comment by PaulHeggarty** [comment]
Short story:  the fix here is to reassign English 'big', because it should not be assigned to 647 at all.  (I’m presuming it's not cognate with the English word 'smoke' -- but even if it were, for CoBL purposes there should be separate, duplicated cognate sets, one for the meaning smoke, the other for the meaning big.)  

Interestingly, this error seems to have crept in during CoBL, perhaps during cognate class reassignments, splitting, or something, and perhaps just by a fat finger, or by some programming bug.  Because it was not there in IELex, see:  
![screenshot - 2016-11-21 00_45_29](https://cloud.githubusercontent.com/assets/8819910/20467256/668e34ce-af84-11e6-8d6e-4c01560740a4.png)

And if you look at the corresponding cognate set it used to be assigned to -- 1342 -- that in CoBL now does not include English big, but still does include Sranan'bigi' (if you switch the language list to all, to show Sranan).  
![screenshot - 2016-11-21 00_52_06](https://cloud.githubusercontent.com/assets/8819910/20467301/36011a28-af85-11e6-8b36-ab42893adccc.png)
![screenshot - 2016-11-21 00_51_08](https://cloud.githubusercontent.com/assets/8819910/20467302/42bf8448-af85-11e6-926f-301051f96f95.png)

The English lexeme could presumably for now be just reassigned to 1342, not 647, but before we do that it would be good to check how this could have happened in the first place, and make sure it can’t happen again:  a lexeme being assigned to a cognate set that does not exist in that meaning.
![screenshot - 2016-11-21 00_52_06](https://cloud.githubusercontent.com/assets/8819910/20467301/36011a28-af85-11e6-8b36-ab42893adccc.png)

**Comment by PaulHeggarty** [comment]
We now need:
- [ ] A failsafe to stop a Cog ID being changed to a different Cog ID that is not valid for the same meaning.
- [ ] A search to find all cases of this happening anywhere in the database, to fix them manually.
Jakob, can you work on both of these?!

**Comment by runjak** [comment]
Yes, I can work on both of these.
The possibility for this was opened up at the latest when we allowed to assign cognate classes by entering their aliases and ids directly.

Have a look at the `Cog. Alias` column in this form (1m or 1l view):
![screenshot_2016-11-21_10-32-55](https://cloud.githubusercontent.com/assets/5417642/20477451/f4968c02-afd5-11e6-8ace-93e5932e9ef0.png)
It accepts the `alias` of a cognate class just as good as the `id` of one.
Given that the id for a cognate class of a different meaning would be entered this would go trough to the database without a problem.

Finding these cases so that they can be corrected shouldn't be hard to do.
Adding the safeguards that something like this cannot be entered again will take a bit longer, but is also possible, of course.

**Comment by PaulHeggarty** [comment]
OK, it looks like this system may be responsible for these data errors.  It has to be fixed.

Everything should go through Cog IDs, fundamentally, since they are unique and the alias letters aren’t, and are potentially ambiguous.  Entering by alias should not really set the alias field directly.   It should:
1. Identify the meaning that corresponds to the record row in which the Cog Alias is being entered.
2. Find the recordset of all cognate sets assigned to that meaning.
3. Within that recordset, find the ID number of whichever 1 cognate set has the Alias letter just typed.
4. Copy that  ID number into the Cog IDs field.
5. That should then automatically insert the corresponding alias letter, which should be the same one just typed.

In fact, unless this cross-check -- limited the entry of a cog set ID to only the cognate sets that correspond to the particular meaning in question -- is built into 'entering by alias' and 'entering by cog set ID', then both entry systems are too dangerous and not really fit for purpose.

**Comment by runjak** [comment]
I've written some code to search for cognate classes that have several meanings:
```bash
…/CoBL (git)-[\#352] % python manage.py findCognateClassesCrossingMeanings
Cognate class 575 has multiple meanings: set([16, 19]).
Cognate class 647 has multiple meanings: set([11, 149]).
Cognate class 2546 has multiple meanings: set([5, 85]).
```

The corresponding links are:
* http://cobl.info/cognate/575/
* http://cobl.info/cognate/647/
* http://cobl.info/cognate/2546/

For `575` we cannot directly see the offending lexeme entry, but we can figure it out by the given meaning id, which is `19`. Visiting `/meaning/19` forwards us to `/meaning/breathe/languagelist/Current/` so this should be an entry that results from a not swadesh term entry and should not even be considered for the exports.

**Comment by PaulHeggarty** [comment]
Great, thanks.  Reassured to see that this is not a big problem, then.  Is it safe for us now to fix these in the data, or would you rather keep them for now to diagnose how/when they occurred?  I’d say we can delete.  Thoughts, anyone?   
So presumably, Leszek was just sharp-eyed and lucky to have noticed a very rare case.  An important one for ensuring it can’t arise again, though.

**Comment by PaulHeggarty** [comment]
For http://cobl.info/cognate/575/, by the way, you just have to switch language list to 'all' to find the problem:

![screenshot - 2016-11-21 12_49_47](https://cloud.githubusercontent.com/assets/8819910/20481756/1900d990-afe9-11e6-8f46-9a1c4849f6bc.png)

**Comment by runjak** [comment]
Thanks - the changing the language list for `575` appears logical in hindsight, but didn't occur to me. I'd be fine with the problematic entries being deleted. But I will check how this can happen nonetheless.

**Comment by runjak** [comment]
I just had a look at the database snapshot from this morning, and the problematic cognate classes are still the same as [4 days ago](#issuecomment-261913339).

Also I've implemented a check to make sure we don't get such cases trough the means I found earlier.

**Comment by runjak** [comment]
I've just deployed the mentioned check.
The remaining thing to do here would be to clean up the false entries in cognate classes `575`, `647` and `2546`.
Since this is dataentry I don't assume to be fit for this and would feel better if someone else can clean these 3 cases up.

**Comment by runjak** [comment]
I've just had a look at the database, and the three cognate classes mentioned still appear to be crossing different meanings:
* [575](http://cobl.info/cognate/575/)
* [647](http://cobl.info/cognate/647/)
* [2546](http://cobl.info/cognate/2546/)

Note that for `575` this only becomes apparent when viewing the `all` language and meaning lists.

@cormacanderson, @PaulHeggarty is it OK to just split these cases into several classes?

**Comment by runjak** [comment]
I just checked for cognate classes that contain different meanings again,
and am happy to report that we don't have such cases in the database any more.

From that I infer that we didn't get any new unwanted cases in the last 22 days.
I'm closing this issue because I believe that there's nothing left to do with it.
