### ISSUE TITLE
Add Root language column immediately after root form

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#90]
This needs doing in both views of the lexemes table, i.e. by 1 language and by 1 meaning.
We'll have to start thinking again about how to save some horizontal space.
We maybe should also use standard abbreviations for the languages.

**Comment by runjak** [comment]
I see that there is a `root_language` field in the `lexicon_cognateclass` table that I shall use for this. I'll use this opportunity to also clean up the code currently used for the `root_form` field that appears to be kind of [hacky](https://github.com/lingdb/CoBL/commit/5e3c8d06e823e0ebb9d621028468f86e5504dc8d) and hard to extend.

**Comment by runjak** [comment]
I've added the `root_language` field, and cleaned up the code I've criticized.
The only problem left is this:
If there are many entries with the same `root_form` and `root_language` fields,
these are currently sent in all together.
This means that all of the fields need to be changed or else something like this can happen:

1. Change only one of the `Root Language` fields to `bar`
2. Save
3. Observer that the fields may still hold `foo` because one of them got written later than the `bar` field.

![mirror](https://cloud.githubusercontent.com/assets/5417642/13496185/1258582a-e14f-11e5-95a8-aa6988311156.png)

Possible solutions to this would be:
* Mirror the fields content in the browser so that all the necessary fields always hold the same values.
* Send only fields that changed by using something like for the translation interface in the SoundComparisons website. Since we want this anyway it would likely make sense to introduce it now instead of a mirror solution that would likely be superseded by this one .

**Comment by cormacanderson** [comment]
I don't entirely follow what is going on in that example, but the important thing is that they change in unison, as currently happens with the "root form" field, where if it is changed for one entry, then it is changed for all of them.

**Comment by runjak** [comment]
I see - that already clarifies how I will continue work here.
